In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("nph-nstedAPI.csv")

In [9]:
df.head()

        pl_name pl_discmethod   pl_orbper  pl_radj  pl_bmassj  pl_dens
0  Kepler-138 c       Transit   13.781300    0.107    0.00620      6.2
1  Kepler-138 d       Transit   23.088100    0.108    0.00201      2.1
2  Kepler-139 b       Transit   15.771044    0.262        NaN      NaN
3  Kepler-139 c       Transit  157.072878    0.302        NaN      NaN
4  Kepler-140 b       Transit    3.254270    0.144        NaN      NaN

In [10]:
df.shape

(4301, 6)

In [7]:
df.dropna

<bound method DataFrame.dropna of             pl_name pl_discmethod   pl_orbper  pl_radj  pl_bmassj  pl_dens
0      Kepler-138 c       Transit   13.781300    0.107    0.00620      6.2
1      Kepler-138 d       Transit   23.088100    0.108    0.00201      2.1
2      Kepler-139 b       Transit   15.771044    0.262        NaN      NaN
3      Kepler-139 c       Transit  157.072878    0.302        NaN      NaN
4      Kepler-140 b       Transit    3.254270    0.144        NaN      NaN
...             ...           ...         ...      ...        ...      ...
4296  Kepler-1514 c       Transit   10.514100    0.118        NaN      NaN
4297  Kepler-1698 b       Transit    1.210700    0.096        NaN      NaN
4298  Kepler-1699 b       Transit    3.490820    0.140        NaN      NaN
4299  Kepler-1700 b       Transit  234.239000    0.259        NaN      NaN
4300  Kepler-1701 b       Transit  169.134000    0.198        NaN      NaN

[4301 rows x 6 columns]>

In [11]:
df1 = df.dropna()

In [14]:
df1[df1['pl_orbper']>200]

            pl_name pl_discmethod  pl_orbper  pl_radj  pl_bmassj  pl_dens
126     Kepler-22 b       Transit   289.8623    0.212    0.11300   14.700
200     Kepler-16 b       Transit   228.7760    0.754    0.33300    0.964
205     Kepler-34 b       Transit   288.8220    0.764    0.22000    0.613
227     Kepler-47 c       Transit   303.2270    0.415    0.00997    0.170
3795  Kepler-1654 b       Transit  1047.8356    0.819    0.50000    1.200
3954    KOI-1783.02       Transit   284.2150    0.485    0.04720    0.510
4134   Kepler-462 c       Transit   207.6200    0.357    0.01888    0.400

In [17]:
df[df['pl_orbper']>360]

          pl_name    pl_discmethod  pl_orbper  pl_radj  pl_bmassj  pl_dens
25     HAT-P-44 c  Radial Velocity    872.200      NaN    4.00000      NaN
37     HD 85390 b  Radial Velocity    799.520      NaN    0.09900      NaN
40     HD 86226 b  Radial Velocity   1628.000      NaN    0.45000      NaN
41     HD 86264 b  Radial Velocity   1475.000      NaN    7.00000      NaN
42     HD 87883 b  Radial Velocity   2754.000      NaN    1.54000      NaN
...           ...              ...        ...      ...        ...      ...
4195  HD 125390 b  Radial Velocity   1756.200      NaN   22.16000      NaN
4244  HD 210193 b  Radial Velocity    649.918      NaN    0.48170      NaN
4248  HD 102843 b  Radial Velocity   3090.942      NaN    0.35837      NaN
4261     GJ 317 c  Radial Velocity   6739.323      NaN    1.64396      NaN
4276  HD 221420 b  Radial Velocity  22482.000      NaN    9.70000      NaN

[455 rows x 6 columns]

In [18]:
df[idx==1000]

KeyError: 1000